name:                functor-combinators
version:             0.1.0.0
github:              "mstksg/functor-combinators"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2019"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Tools for functor combinator-based program design
category:            Data

description: |
    Tools for working with *functor combinators*: types that take functors (or
    other indexed types) and returns a new functor that "enhances" or "mixes"
    them in some way.  In the process, you can design featureful programs by
    composing smaller "primitives" using basic unversal combinators.

    The main entry point is "Data.Functor.Combinators", but more fine-grained
    functionality and extra combinators (some of them re-implementations for
    compatibility) are available in other modules as well.

    See the README for a quick overview, and also
    <https://blog.jle.im/entry/functor-combinatorpedia.html> for an in-depth
    dive into the motivation behind functor combinator-driven development,
    examples of the functor combinators in this library, and details about how
    to use these abstractions!

ghc-options:
- -Wall
- -Wcompat
- -Wredundant-constraints
- -Werror=incomplete-patterns

dependencies:
- base >= 4.7 && < 5
- bifunctors
- free
- nonempty-containers
- semigroupoids
- tagged
- transformers

library:
  source-dirs: src
  other-modules:
  - Data.HFunctor.Internal
  dependencies:
  - comonad
  - constraints
  - containers
  - deriving-compat
  - kan-extensions
  - mmorph
  - mtl
  - natural-transformation
  - pointed
  - profunctors
  - recursion-schemes
  - these
  - trivial-constraint >= 0.5

tests:
  functor-combinators-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hedgehog >= 1.0
    - functor-combinators
    - tasty
    - tasty-hedgehog >= 1.0
    - dependent-sum
